version: "3"
services:
  mysql:
    image: mysql
    restart: always
    ports:
      - 8080:8080
    environment:
      MYSQL_DATABASE: "books"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - mysql-data:/data/db
volumes:
  mysql-data:
    #driver: local
